### ISSUE TITLE
ConcurrentModificationException in EntityController.update()

### ISSUE THREAD

**Issue by mrpho3nix** [AMatutat/pmdungeon#23]
public void update() {
        for (IEntity obj : dungeonEntitys) {
            if (obj.deleteable()) removeEntity(obj);
            else obj.update();
        }
    }

removes entities while iterating through the entityList causes ConcurrentModificationException

**Comment by Umang228** [comment]
Assign this to me...

**Comment by cagix** [comment]
should be fixed w/ #25

**Comment by AMatutat** [comment]
Is fixed. 
Will be shiped with 1.1.4.0
