### ISSUE TITLE
Merge Sub-Projects

### ISSUE THREAD

**Issue by cagix** [AMatutat/pmdungeon#44]
the separation into `core` and `desktop`, even if it appears elegant and future-proof, does add a certain complexity that does not seem justified to me at the moment (and for the foreseeable future). next year, when we have students work directly with this repo as a default, this could^Wwill become another possible source of potential problems. 

should we merge `core` and `desktop` for the time being?

this would also affect build skripts (gradle, maven) and maybe documentation.

**Comment by AMatutat** [comment]
Okay..... 
Guess i can split it again if needed

**Comment by cagix** [comment]
@AMatutat But, if we do, please let's close those Gradle and Maven PRs (#38, #39, #48) first. Otherwise we will probably open the third hell ;)
