### ISSUE TITLE
add ant skripts

### ISSUE THREAD

**Issue by cagix** [AMatutat/pmdungeon#45]
add ant build skripts w/ same functionality as the already existing gradle scripts and the future maven skripts (#38, #39)

**Comment by Tobias321** [comment]
Is Ant Ivy allowed for dependency management? The ivy jar file would have to in the project too.

**Comment by cagix** [comment]
> Is Ant Ivy allowed for dependency management? The ivy jar file would have to in the project too.

sure :)
