### ISSUE TITLE
setup git-hook with an external formatter

### ISSUE THREAD

**Issue by AMatutat** [AMatutat/pmdungeon#68]
> should we add a git-hook with an external formatter? then we would no longer be dependent on the various ide's and their formatters/styles ... (cagix)

**Comment by cagix** [comment]
https://github.com/google/google-java-format/

**Comment by cagix** [comment]
https://clang.llvm.org/docs/ClangFormat.html

**Comment by cagix** [comment]
https://github.com/axel-op/googlejavaformat-action

**Comment by cagix** [comment]
siehe "Third-party integrations" https://github.com/google/google-java-format

**Comment by AMatutat** [comment]
> https://github.com/axel-op/googlejavaformat-action 

Got a running test. Will take a deeper look in the configuration options and then set this up.

**Comment by AMatutat** [comment]
Ok it is active now.
Code is now formated AFTER it gets pushed on the master.

**Comment by cagix** [comment]
@AMatutat 👍  btw, does this action also commit the (re-) formatted code?

**Comment by cagix** [comment]
@AMatutat also, should we trigger this action for merge events, only? i assume this action performs a commit after formatting, so we'd get a second commit to each real commit. this could be annoying ;)

**Comment by cagix** [comment]
@AMatutat Are you sure that this action actually works? It shows "green" but there seems to be an error inside?
<img width="1364" alt="Screenshot 2021-06-24 at 10 31 16" src="https://user-images.githubusercontent.com/20356276/123230487-9521a780-d4d7-11eb-93a5-e0e967ee88b6.png">

**Comment by AMatutat** [comment]
> @AMatutat Are you sure that this action actually works? It shows "green" but there seems to be an error inside?

Hmm funny, no Error for me. 
Are you on a Mac?

![image](https://user-images.githubusercontent.com/32962412/123240625-c05cc480-d4e0-11eb-9be5-129b2d92dd76.png)

**Comment by cagix** [comment]
wtf?! what is happening here? isn't this the log of an action that has already been executed? why is this green in one view/browser and red in another?

**Comment by AMatutat** [comment]
Black magic?

**Comment by AMatutat** [comment]
>  i assume this action performs a commit after formatting, so we'd get a second commit to each real commit. this could be annoying ;)

Not sure i got you right, so:
I commit my change with -m "Best code ever", push it to the master and then the action will do a formatting commit -m "Google Java Format"

The action can also perform on merge_request, but this shouldn't work while using forks. The action needs permission to commit, and this permission is for this repo only.

**Comment by cagix** [comment]
> > i assume this action performs a commit after formatting, so we'd get a second commit to each real commit. this could be annoying ;)
> 
> Not sure i got you right, so:
> I commit my change with -m "Best code ever", push it to the master and then the action will do a formatting commit -m "Google Java Format"

that's what i meant. you make a commit, push it and then the github action adds a format commit each time. 

i think it would be nicer if this could be done within the first (actual) commit. of course, this can only be done via git hooks and not via a github action.

that's why i suggested to think about doing this action only during a merge. the whole project should be formatted, and you only have to reformat the new code from the pull-request during the merge... 

> The action can also perform on merge_request, but this shouldn't work while using forks. The action needs permission to commit, and this permission is for this repo only.

of course, this is not possible in a fork. but it would be sufficient if the action was carried out here in the repo when merging (accepting a pull request).

**Comment by cagix** [comment]
ah, i forgot that we always work with pull requests here and do not directly commit to the master ... 

then it makes sense.

**Comment by cagix** [comment]
@AMatutat i just triggered the job via web-gui, and got this error "Error: The command 'git' failed with exit code 1" ... am i not allowed to start the job? well, it did start, but had an error in the format action. hmmm.

and my os shouldn't interfere here, since i've started the action via browser and the runner itself is linux/ubuntu.

**Comment by AMatutat** [comment]
@cagix got the same error. 

```
WARNING: Illegal reflective access by com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer (file:/home/runner/google-java-format.jar) to field com.sun.tools.javac.parser.JavaTokenizer.reader
```
and
```
 error: failed to push some refs to 'https://github.com/AMatutat/pmdungeon.git'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
  Error: The command 'git' failed with exit code 1
```

That confuses me.
Maybe It's because there is nothing to change?

**Comment by AMatutat** [comment]
Ok I just merged a test commit and then the job executes fine. If i manual rerun the action, it fails.
So on paper the action works, if we don't touch it.

**Comment by cagix** [comment]
crossing fingers 🙈
