### ISSUE TITLE
Version control for all build scripts

### ISSUE THREAD

**Issue by AMatutat** [AMatutat/pmdungeon#69]
For didactic reason, this project should contain ANT, Maven and Gradle as build scripts.
Is there a chance to somehow define and maintain the version numbers in a common file?

**Comment by Tobias321** [comment]
I don't think, this is impossible...:

https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties
https://ant.apache.org/manual/Tasks/loadproperties.html
http://www.mojohaus.org/properties-maven-plugin/

Think, we need a `gradle.properties` file (for the version numbers). This file could be also be read from Ant and Maven.

Should i try? But first it seems good to close/solve/merge the depending pr's... #57 #58 #65

**Comment by AMatutat** [comment]
> But first it seems good to close/solve/merge the depending pr's... #57 #58 #65

Yea, lets just finish what we started and come back to this later.

**Comment by Tobias321** [comment]
> > But first it seems good to close/solve/merge the depending pr's... #57 #58 #65
> 
> Yea, lets just finish what we started and come back to this later.

good thought 👍🏻

**Comment by Tobias321** [comment]
we have that already for Ant, but for Maven it's not that easy...

i tried to add:
```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>properties-maven-plugin</artifactId>
    <version>1.0.0</version>
    <executions>
        <execution>
            <phase>initialize</phase>
            <goals>
                <goal>read-project-properties</goal>
            </goals>
            <configuration>
                <files>
                    <file>${project.basedir}/build.properties</file>
                </files>
            </configuration>
        </execution>
    </executions>
</plugin>
```

but if you than reference: `<version>${gsonVersion}</version>` everything is exploding.
