### ISSUE TITLE
Clean up .gitignore

### ISSUE THREAD

**Issue by Tobias321** [AMatutat/pmdungeon#78]
There are some entries in the `.gitignore` that are redundant or could be rearranged and labeled correctly.

We should do this after the pending PRs, with changes to the `.gitignore`.

**Comment by Swarnima-27** [comment]
Hi @Tobias321 ,can i work on this?

**Comment by Tobias321** [comment]
@Swarnima-27 sure, you could 🙂

**Comment by Tobias321** [comment]
@Swarnima-27 the works on `.gitignore` are now all done. You're ready to go. 🙂

**Comment by Tobias321** [comment]
@cagix nope
