### ISSUE TITLE
Doc: IDE integration

### ISSUE THREAD

**Issue by Tobias321** [AMatutat/pmdungeon#80]
Maybe we should add some simple steps to the docs, how to integrate the project into the different IDEs (at least for eclipse and intellij,...). Or is that "general knowledge"?

**Comment by cagix** [comment]
yes, we are talking about the second semester ... so that makes a lot of sense to me :)

**Comment by AMatutat** [comment]
sounds good.
Guess we should add that to the docs/manual_DE/EN

**Comment by Tobias321** [comment]
my English language is not that good, but i can try it

**Comment by AMatutat** [comment]
start with the german version. 
Later we can throw our manual in DeepL

**Comment by AMatutat** [comment]
#85 for eclipse is merged
