### ISSUE TITLE
EntityController.addEntity(null) adds null-object, crashes game later while rendering

### ISSUE THREAD

**Issue by Alizame** [AMatutat/pmdungeon#92]
EntityController.addEntity(null) actually adds a null-object to it's internal list.

This is problematic, because it produces a NullPointerException later while updating the entitys (and that happens only while rendering). 
So for a user this looks like some kind of rendering related error and may lead him the wrong way.

---

Fix: check for null in addEntity(), if null -> don't add it (or throw an exception here? so it doesnt fail silently?).

**Comment by AMatutat** [comment]
`EntityController#addEntity` should throw a Nullpointer.
